# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
