# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171208_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='{PWD}/FlowerLight/static/img/default_flower_image.png', upload_to='')),
                ('type', models.IntegerField(choices=[(0, 'букеты'), (1, 'отдельные цветы для букета'), (2, 'живые цветы'), (3, 'семена')], default=0)),
            ],
        )
    ]
