# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20171208_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='{PWD}/FlowerLight/static/img/default_avatar.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Client'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
        ),
    ]
