# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20171208_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
