# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20171215_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='productPictures/default_flower_image.png', upload_to='productPictures'),
        ),
    ]
