# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20171215_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='productPictures/default_flower_image.jpg', upload_to='productPictures'),
        ),
    ]
