# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20171215_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(0, 'букеты'), (1, 'срезанные отдельные цветы'), (2, 'живые цветы'), (3, 'семена')], default=0),
        ),
    ]
