# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='main_app.ProductTag'),
        ),
    ]
